name: Build images

on:
  push:
    branches:
      - master

jobs:
  build-fe:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add frontend build env
        run: |
          echo "${{ secrets.FRONTEND_ENV }}" > frontend/.env

      - name: Set up Docker config for GHCR
        run: |
          mkdir -p ~/.docker
          echo "{\"auths\":{\"ghcr.io\":{\"username\":\"${{ github.actor }}\",\"password\":\"${{ secrets.GITHUB_TOKEN }}\"}}}" > ~/.docker/config.json

      - name: Build and push FE Docker image
        uses: int128/kaniko-action@v1
        with:
          tags: ghcr.io/${{ github.repository }}:latest
          file: ./docker/frontend.ci.Dockerfile
          context: .
          kaniko-args: |
            --single-snapshot

  build-be:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker config for GHCR
        run: |
          mkdir -p ~/.docker
          echo "{\"auths\":{\"ghcr.io\":{\"username\":\"${{ github.actor }}\",\"password\":\"${{ secrets.GITHUB_TOKEN }}\"}}}" > ~/.docker/config.json

      - name: Build and push FE Docker image
        uses: int128/kaniko-action@v1
        with:
          tags: ghcr.io/${{ github.repository }}:latest
          file: ./docker/server.ci.Dockerfile
          context: .
          kaniko-args: |
            --single-snapshot

