name: Build images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push front-end Docker image
        uses: int128/kaniko-action@v1
        with:
          context: .
          dockerfile: docker/fe.Dockerfile
          destination: ghcr.io/${{ github.repository }}/pace-fe:latest
          cache: true
          build_args: |
            --no-snapshot

      - name: Build and push back-end Docker image
        uses: int128/kaniko-action@v1
        with:
          context: .
          dockerfile: docker/server.Dockerfile
          destination: ghcr.io/${{ github.repository }}/pace-be:latest
          cache: true
          build_args: |
            --no-snapshot
